from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package='pubsub',
            executable='talker',
            name='talker1'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener1'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener2'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener3'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener4'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener5'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener6'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener7'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener8'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener9'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener10'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener11'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener12'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener13'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener14'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener15'
        ),
        Node(
            package='pubsub',
            executable='listener',
            name='listener16'
        ),

    ])
